Name: Reusable Build and Tests for .Net core

inputs:
  dotnet-version:
    required: true
  solution-path:
    required: true
  publish-folder:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Create package
      shell: bash
      run: |
        cd ${{ inputs.csproj-path }}
        echo "###### pubish folder is ${{ inputs.publish-folder }}"
        dotnet publish -c Release -o "${{ inputs.publish-folder }}"  
    - name: Upload published package
      uses: actions/upload-artifact@v2
      with: 
        name: publish
        path: ${{ inputs.publish-folder }}
        retention-days: 1
    - name: List artifacts
      shell: bash
      run: |
        pwd
        echo "Listing artifacts"
        ls ${{ inputs.publish-folder }}


