Name: Reusable Build and Tests for .Net core

inputs:
  dotnet-version:
    required: true
  solution-path:
    required: true
  publish-folder:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Build
      shell: bash
      run: |
        echo "solution path is ${{ inputs.solution-path }}"
        cd ${{ inputs.solution-path }}
        dotnet restore
        
        dotnet build --configuration Release --no-restore # set /WarnAsError to fail on warnings
        dotnet publish -c Release -o ${{ inputs.publish-folder }} -r linux-x64   # do this only if rule is not merge request
    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.solution-path }}
        dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
    - name: Visualize test results
      uses: dorny/test-reporter@v1
      if: always()
      with: 
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true  
    - name: Upload published package
      uses: actions/upload-artifact@v2
      with: 
        name: publish
        path: ${{ inputs.publish-folder }}
        retention-days: 1

