name: .NET

on:
  push:
    branches: [ "actions-experiment"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build and analysis
      run: |
        cd Simple/MovieApi/MovieRank/
        dotnet build
    - name: Test
      run: |
        cd Simple/MovieApi/MovieRank/
        dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
    - name: Visualize test results
      uses: dorny/test-reporter@v1
      if: always()
      with: 
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true  
        retention-days: 1

