name: .NET

on:
  push:
    branches: [ "master"]

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish exacutable
        uses: ./.github/actions/package
        with:
          dotnet-version: 6.0.x
          solution-path: Simple/MovieApi/MovieRank/
          publish-folder: "${GITHUB_WORKSPACE}/publish"

    
