name: .NET

on:
  push:
    branches: [ "actions-experiment"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build and analysis
      run: |
        cd Simple/MovieApi/MovieRank/
        dotnet build
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
