name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v3
      - name: Publish exacutable
        uses: ./.github/actions/publish
        with:
          dotnet-version: 6.0.x
          csproj-path: Simple/MovieApi/MovieRank/
          publish-folder: publish

